### ISSUE TITLE
Unsupported browser message

### ISSUE THREAD

**Issue by Aculeo** [MarvinKlein1508/SignaturePad#6]
Thanks for making this control! 

Could you replace this message with something a bit more appropriate?

>  Get a better browser, bro.

Perhaps "Please upgrade to a modern browser to use this feature." The current message isn't exactly appropriate for business apps. :)
Ideally this would be configurable though, so it can be localized.

**Comment by MarvinKlein1508** [comment]
I don't see the need to make it customizable since every [major browser does support ](https://caniuse.com/?search=canvas) it. Only IE 6-8 are missing out which doesn't matter because Blazor apps doesn't work in IE at all.

Could you tell me when you saw the message? Maybe I'm mssing something. But I can change the text, no problem.
